### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by kopr97** [hak86/android_device_huawei_p8litekirin#1]
How's progress ??? :)

**Comment by hak86** [comment]
I got booted finally, now I'm testing the new boot.img with the ramdisk from the first build, i guess it's the problem.

**Comment by DyWN** [comment]
i believe you can make it.
btw what about omni 7? you wont work on it or just hide it for a moment to focus on cm12?

**Comment by hak86** [comment]
i get many errors from java, isn't installed as well, for the moment i'm focus on cm-12.1, i also fix random reboot ;).

**Comment by kopr97** [comment]
When you plan to release another beta ??? ;)

**Comment by hak86** [comment]
not yet, I'm making a private twrp to let me format cust partition too, i have dual sim firmware on single sim device and give me a lot of troubles, even if i install the single sim firmware, i still have dual card managements in settings.

**Comment by hak86** [comment]
![screenshot_2016-09-17-06-16-04](https://cloud.githubusercontent.com/assets/6603252/18607895/5e8b591e-7cda-11e6-93db-4d917772959b.png)

**Comment by kopr97** [comment]
good job :)

**Comment by DyWN** [comment]
there is already twrp that can wipe cust
http://www.htcmania.com/showthread.php?t=1162837
